/*
 * This file was automatically generated by EvoSuite
 */

package org.jsecurity.util;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import java.util.Collection;
import java.util.List;
import java.util.Set;
import org.jsecurity.util.CollectionUtils;

public class CollectionUtilsEvoSuiteTest {


  //Test case number: 1
  /*
   * 1 covered goal:
   * 1 org.jsecurity.util.CollectionUtils.<init>()V: root-Branch
   */
  @Test
  public void test1()  throws Throwable  {
      CollectionUtils collectionUtils0 = new CollectionUtils();
      assertNotNull(collectionUtils0);
  }

  //Test case number: 2
  /*
   * 1 covered goal:
   * 1 org.jsecurity.util.CollectionUtils.emptyCollection(Ljava/lang/Class;)Ljava/util/Collection;: root-Branch
   */
  @Test
  public void test2()  throws Throwable  {
      Class<?> class0 = Object.class;
      Collection<Integer> collection0 = CollectionUtils.emptyCollection((Class<Integer>) class0);
      assertEquals(true, collection0.isEmpty());
  }
}
