/*
 * This file was automatically generated by EvoSuite
 */

package org.jsecurity.util;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import java.util.Set;
import org.jsecurity.authz.Permission;
import org.jsecurity.authz.permission.PermissionResolver;
import org.jsecurity.authz.permission.WildcardPermissionResolver;
import org.jsecurity.util.PermissionUtils;

public class PermissionUtilsEvoSuiteTest {


  //Test case number: 0
  /*
   * 1 covered goal:
   * 1 org.jsecurity.util.PermissionUtils.<init>()V: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      PermissionUtils permissionUtils0 = new PermissionUtils();
      assertNotNull(permissionUtils0);
  }

  //Test case number: 2
  /*
   * 1 covered goal:
   * 1 org.jsecurity.util.PermissionUtils.toPermissionStrings(Ljava/lang/String;)Ljava/util/Set;: I8 Branch 1 IFNULL L44 - true
   */
  @Test
  public void test2()  throws Throwable  {
      Set<String> set0 = PermissionUtils.toPermissionStrings("");
      assertNull(set0);
  }
}
