/*
 * This file was automatically generated by EvoSuite
 */

package net.sf.jniinchi;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import net.sf.jniinchi.INCHI_PARITY;

public class INCHI_PARITYEvoSuiteTest {


  //Test case number: 0
  /*
   * 1 covered goal:
   * 1 net.sf.jniinchi.INCHI_PARITY.getIndx()I: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      INCHI_PARITY iNCHI_PARITY0 = INCHI_PARITY.UNDEFINED;
      int int0 = iNCHI_PARITY0.getIndx();
      assertEquals(4, int0);
  }

  //Test case number: 1
  /*
   * 6 covered goals:
   * 1 net.sf.jniinchi.INCHI_PARITY.getValue(I)Lnet/sf/jniinchi/INCHI_PARITY;: I3 Branch 1 TABLESWITCH L72 Case 0 - true
   * 2 net.sf.jniinchi.INCHI_PARITY.getValue(I)Lnet/sf/jniinchi/INCHI_PARITY;: I3 Branch 2 TABLESWITCH L72 Case 1 - false
   * 3 net.sf.jniinchi.INCHI_PARITY.getValue(I)Lnet/sf/jniinchi/INCHI_PARITY;: I3 Branch 3 TABLESWITCH L72 Case 2 - false
   * 4 net.sf.jniinchi.INCHI_PARITY.getValue(I)Lnet/sf/jniinchi/INCHI_PARITY;: I3 Branch 4 TABLESWITCH L72 Case 3 - false
   * 5 net.sf.jniinchi.INCHI_PARITY.getValue(I)Lnet/sf/jniinchi/INCHI_PARITY;: I3 Branch 5 TABLESWITCH L72 Case 4 - false
   * 6 net.sf.jniinchi.INCHI_PARITY.getValue(I)Lnet/sf/jniinchi/INCHI_PARITY;: I3 Branch 6 TABLESWITCH L72 Default-Case - false
   */
  @Test
  public void test1()  throws Throwable  {
      INCHI_PARITY iNCHI_PARITY0 = INCHI_PARITY.getValue(0);
      assertEquals(INCHI_PARITY.NONE, iNCHI_PARITY0);
  }

  //Test case number: 2
  /*
   * 2 covered goals:
   * 1 net.sf.jniinchi.INCHI_PARITY.getValue(I)Lnet/sf/jniinchi/INCHI_PARITY;: I3 Branch 1 TABLESWITCH L72 Case 0 - false
   * 2 net.sf.jniinchi.INCHI_PARITY.getValue(I)Lnet/sf/jniinchi/INCHI_PARITY;: I3 Branch 5 TABLESWITCH L72 Case 4 - true
   */
  @Test
  public void test2()  throws Throwable  {
      INCHI_PARITY iNCHI_PARITY0 = INCHI_PARITY.getValue(4);
      assertEquals(INCHI_PARITY.UNDEFINED, iNCHI_PARITY0);
  }

  //Test case number: 3
  /*
   * 1 covered goal:
   * 1 net.sf.jniinchi.INCHI_PARITY.getValue(I)Lnet/sf/jniinchi/INCHI_PARITY;: I3 Branch 2 TABLESWITCH L72 Case 1 - true
   */
  @Test
  public void test3()  throws Throwable  {
      INCHI_PARITY iNCHI_PARITY0 = INCHI_PARITY.getValue(1);
      assertEquals(INCHI_PARITY.ODD, iNCHI_PARITY0);
  }

  //Test case number: 4
  /*
   * 1 covered goal:
   * 1 net.sf.jniinchi.INCHI_PARITY.getValue(I)Lnet/sf/jniinchi/INCHI_PARITY;: I3 Branch 3 TABLESWITCH L72 Case 2 - true
   */
  @Test
  public void test4()  throws Throwable  {
      INCHI_PARITY iNCHI_PARITY0 = INCHI_PARITY.getValue(2);
      assertEquals(INCHI_PARITY.EVEN, iNCHI_PARITY0);
  }

  //Test case number: 5
  /*
   * 2 covered goals:
   * 1 net.sf.jniinchi.INCHI_PARITY.getValue(I)Lnet/sf/jniinchi/INCHI_PARITY;: I3 Branch 4 TABLESWITCH L72 Case 3 - true
   * 2 net.sf.jniinchi.INCHI_PARITY.getValue(I)Lnet/sf/jniinchi/INCHI_PARITY;: I3 Branch 6 TABLESWITCH L72 Default-Case - false
   */
  @Test
  public void test5()  throws Throwable  {
      INCHI_PARITY iNCHI_PARITY0 = INCHI_PARITY.getValue(3);
      assertEquals(INCHI_PARITY.UNKNOWN, iNCHI_PARITY0);
  }

  //Test case number: 6
  /*
   * 6 covered goals:
   * 1 net.sf.jniinchi.INCHI_PARITY.getValue(I)Lnet/sf/jniinchi/INCHI_PARITY;: I3 Branch 6 TABLESWITCH L72 Default-Case - true
   * 2 net.sf.jniinchi.INCHI_PARITY.getValue(I)Lnet/sf/jniinchi/INCHI_PARITY;: I3 Branch 1 TABLESWITCH L72 Case 0 - false
   * 3 net.sf.jniinchi.INCHI_PARITY.getValue(I)Lnet/sf/jniinchi/INCHI_PARITY;: I3 Branch 2 TABLESWITCH L72 Case 1 - false
   * 4 net.sf.jniinchi.INCHI_PARITY.getValue(I)Lnet/sf/jniinchi/INCHI_PARITY;: I3 Branch 3 TABLESWITCH L72 Case 2 - false
   * 5 net.sf.jniinchi.INCHI_PARITY.getValue(I)Lnet/sf/jniinchi/INCHI_PARITY;: I3 Branch 4 TABLESWITCH L72 Case 3 - false
   * 6 net.sf.jniinchi.INCHI_PARITY.getValue(I)Lnet/sf/jniinchi/INCHI_PARITY;: I3 Branch 5 TABLESWITCH L72 Case 4 - false
   */
  @Test
  public void test6()  throws Throwable  {
      INCHI_PARITY.getValue(1706);
  }
}
