/*
 * This file was automatically generated by EvoSuite
 */

package org.jsecurity.web;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import org.jsecurity.web.RedirectView;

public class RedirectViewEvoSuiteTest {


  //Test case number: 0
  /*
   * 3 covered goals:
   * 1 org.jsecurity.web.RedirectView.setUrl(Ljava/lang/String;)V: root-Branch
   * 2 org.jsecurity.web.RedirectView.<init>(Ljava/lang/String;ZZ)V: root-Branch
   * 3 org.jsecurity.web.RedirectView.<init>(Ljava/lang/String;)V: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      RedirectView redirectView0 = new RedirectView("", true, true);
  }

  //Test case number: 1
  /*
   * 1 covered goal:
   * 1 org.jsecurity.web.RedirectView.<init>()V: root-Branch
   */
  @Test
  public void test1()  throws Throwable  {
      RedirectView redirectView0 = new RedirectView();
  }

  //Test case number: 2
  /*
   * 3 covered goals:
   * 1 org.jsecurity.web.RedirectView.<init>(Ljava/lang/String;Z)V: root-Branch
   * 2 org.jsecurity.web.RedirectView.setUrl(Ljava/lang/String;)V: root-Branch
   * 3 org.jsecurity.web.RedirectView.<init>(Ljava/lang/String;)V: root-Branch
   */
  @Test
  public void test2()  throws Throwable  {
      RedirectView redirectView0 = new RedirectView("", true);
  }
}
