/*
 * This file was automatically generated by EvoSuite
 */

package org.jsecurity.web;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import org.jsecurity.web.WebRememberMeManager;
import org.jsecurity.web.attr.RequestParamAttribute;

public class WebRememberMeManagerEvoSuiteTest {


  //Test case number: 2
  /*
   * 1 covered goal:
   * 1 org.jsecurity.web.WebRememberMeManager.getIdentityAttribute()Lorg/jsecurity/web/attr/WebAttribute;: root-Branch
   */
  @Test
  public void test2()  throws Throwable  {
      WebRememberMeManager webRememberMeManager0 = new WebRememberMeManager();
      webRememberMeManager0.getIdentityAttribute();
  }

  //Test case number: 3
  /*
   * 1 covered goal:
   * 1 org.jsecurity.web.WebRememberMeManager.setCookieSecure(Z)V: root-Branch
   */
  @Test
  public void test3()  throws Throwable  {
      WebRememberMeManager webRememberMeManager0 = new WebRememberMeManager();
      webRememberMeManager0.setCookieSecure(true);
      assertNull(webRememberMeManager0.getCookiePath());
  }

  //Test case number: 7
  /*
   * 3 covered goals:
   * 1 org.jsecurity.web.WebRememberMeManager.assertCookieAttribute()V: I5 Branch 1 IFNE L88 - false
   * 2 org.jsecurity.web.WebRememberMeManager.setIdentityAttribute(Lorg/jsecurity/web/attr/WebAttribute;)V: root-Branch
   * 3 org.jsecurity.web.WebRememberMeManager.setCookieMaxAge(I)V: root-Branch
   */
  @Test
  public void test7()  throws Throwable  {
      WebRememberMeManager webRememberMeManager0 = new WebRememberMeManager();
      RequestParamAttribute<String> requestParamAttribute0 = new RequestParamAttribute<String>();
  }

  //Test case number: 8
  /*
   * 1 covered goal:
   * 1 org.jsecurity.web.WebRememberMeManager.setCookiePath(Ljava/lang/String;)V: root-Branch
   */
  @Test
  public void test8()  throws Throwable  {
      WebRememberMeManager webRememberMeManager0 = new WebRememberMeManager();
      webRememberMeManager0.setCookiePath("rememberMe");
      assertEquals("rememberMe", webRememberMeManager0.getCookiePath());
  }

  //Test case number: 10
  /*
   * 1 covered goal:
   * 1 org.jsecurity.web.WebRememberMeManager.setCookieName(Ljava/lang/String;)V: root-Branch
   */
  @Test
  public void test10()  throws Throwable  {
      WebRememberMeManager webRememberMeManager0 = new WebRememberMeManager();
      webRememberMeManager0.setCookieName("rememberMe");
      assertEquals("rememberMe", webRememberMeManager0.getCookieName());
  }

  //Test case number: 11
  /*
   * 3 covered goals:
   * 1 org.jsecurity.web.WebRememberMeManager.setCookieMaxAge(I)V: root-Branch
   * 2 org.jsecurity.web.WebRememberMeManager.<init>()V: root-Branch
   * 3 org.jsecurity.web.WebRememberMeManager.assertCookieAttribute()V: I5 Branch 1 IFNE L88 - true
   */
  @Test
  public void test11()  throws Throwable  {
      WebRememberMeManager webRememberMeManager0 = new WebRememberMeManager();
      webRememberMeManager0.setCookieMaxAge(0);
      assertEquals("rememberMe", webRememberMeManager0.getCookieName());
  }
}
