/*
 * This file was automatically generated by EvoSuite
 */

package org.databene.jdbacl.model;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;

public class FKChangeRuleEvoSuiteTest {

}
