/*
 * This file was automatically generated by EvoSuite
 */

package org.jsecurity.codec;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import org.jsecurity.codec.Hex;

public class HexEvoSuiteTest {


  //Test case number: 0
  /*
   * 1 covered goal:
   * 1 org.jsecurity.codec.Hex.<init>()V: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      Hex hex0 = new Hex();
      assertNotNull(hex0);
  }

  //Test case number: 5
  /*
   * 1 covered goal:
   * 1 org.jsecurity.codec.Hex.toDigit(CI)I: I10 Branch 4 IF_ICMPNE L156 - true
   */
  @Test
  public void test5()  throws Throwable  {
      int int0 = Hex.toDigit('F', 'F');
      assertEquals(15, int0);
  }
}
