/*
 * This file was automatically generated by EvoSuite
 */

package org.jsecurity.authz.permission;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import org.jsecurity.authz.permission.WildcardPermissionResolver;

public class WildcardPermissionResolverEvoSuiteTest {


  //Test case number: 0
  /*
   * 2 covered goals:
   * 1 org.jsecurity.authz.permission.WildcardPermissionResolver.resolvePermission(Ljava/lang/String;)Lorg/jsecurity/authz/Permission;: root-Branch
   * 2 org.jsecurity.authz.permission.WildcardPermissionResolver.<init>()V: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      WildcardPermissionResolver wildcardPermissionResolver0 = new WildcardPermissionResolver();
      // Undeclared exception!
      try {
        wildcardPermissionResolver0.resolvePermission("");
        fail("Expecting exception: IllegalArgumentException");
      } catch(IllegalArgumentException e) {
        /*
         * Wildcard string cannot be null or empty. Make sure permission strings are properly formatted.
         */
      }
  }
}
