/*
 * This file was automatically generated by EvoSuite
 */

package org.jsecurity.authz.aop;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import org.jsecurity.aop.MethodInvocation;
import org.jsecurity.authz.aop.PermissionAnnotationMethodInterceptor;

public class AuthorizingAnnotationMethodInterceptorEvoSuiteTest {
}
