/*
 * This file was automatically generated by EvoSuite
 */

package org.jsecurity.authz.aop;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import java.lang.annotation.Annotation;
import org.jsecurity.authz.AuthorizationException;
import org.jsecurity.authz.aop.GuestAnnotationHandler;

public class GuestAnnotationHandlerEvoSuiteTest {


  //Test case number: 0
  /*
   * 2 covered goals:
   * 1 org.jsecurity.authz.aop.GuestAnnotationHandler.assertAuthorized(Ljava/lang/annotation/Annotation;)V: I4 Branch 1 IFEQ L60 - true
   * 2 org.jsecurity.authz.aop.GuestAnnotationHandler.<init>()V: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      GuestAnnotationHandler guestAnnotationHandler0 = new GuestAnnotationHandler();
      guestAnnotationHandler0.assertAuthorized((Annotation) null);
  }
}
