/*
 * This file was automatically generated by EvoSuite
 */

package net.sourceforge.schemaspy.view;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import net.sourceforge.schemaspy.view.HtmlFormatter;

public class HtmlFormatterEvoSuiteTest {


  //Test case number: 0
  /*
   * 1 covered goal:
   * 1 net.sourceforge.schemaspy.view.HtmlFormatter.<init>()V: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      HtmlFormatter htmlFormatter0 = new HtmlFormatter();
      assertEquals(true, htmlFormatter0.sourceForgeLogoEnabled());
  }
}
