/*
 * This file was automatically generated by EvoSuite
 */

package net.sourceforge.schemaspy.view;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import java.io.IOException;
import net.sourceforge.schemaspy.util.LineWriter;
import net.sourceforge.schemaspy.view.StyleSheet;

public class StyleSheetEvoSuiteTest {


  //Test case number: 0
  /*
   * 2 covered goals:
   * 1 net.sourceforge.schemaspy.view.StyleSheet.write(Lnet/sourceforge/schemaspy/util/LineWriter;)V: root-Branch
   * 2 net.sourceforge.schemaspy.view.StyleSheet.getInstance()Lnet/sourceforge/schemaspy/view/StyleSheet;: I3 Branch 14 IFNONNULL L118 - true
   */
  @Test
  public void test0()  throws Throwable  {
      StyleSheet styleSheet0 = StyleSheet.getInstance();
      // Undeclared exception!
      try {
        styleSheet0.write((LineWriter) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  //Test case number: 1
  /*
   * 1 covered goal:
   * 1 net.sourceforge.schemaspy.view.StyleSheet.getBodyBackground()Ljava/lang/String;: I4 Branch 19 IFNONNULL L188 - true
   */
  @Test
  public void test1()  throws Throwable  {
      StyleSheet styleSheet0 = StyleSheet.getInstance();
      String string0 = styleSheet0.getBodyBackground();
      assertEquals("#f7f7f7", string0);
  }

  //Test case number: 2
  /*
   * 1 covered goal:
   * 1 net.sourceforge.schemaspy.view.StyleSheet.getTableBackground()Ljava/lang/String;: I4 Branch 20 IFNONNULL L195 - true
   */
  @Test
  public void test2()  throws Throwable  {
      StyleSheet styleSheet0 = StyleSheet.getInstance();
      String string0 = styleSheet0.getTableBackground();
      assertEquals("#ffffff", string0);
  }

  //Test case number: 3
  /*
   * 1 covered goal:
   * 1 net.sourceforge.schemaspy.view.StyleSheet.getTableHeadBackground()Ljava/lang/String;: I4 Branch 21 IFNONNULL L202 - true
   */
  @Test
  public void test3()  throws Throwable  {
      StyleSheet styleSheet0 = StyleSheet.getInstance();
      String string0 = styleSheet0.getTableHeadBackground();
      assertEquals("#9bab96", string0);
  }

  //Test case number: 4
  /*
   * 1 covered goal:
   * 1 net.sourceforge.schemaspy.view.StyleSheet.getPrimaryKeyBackground()Ljava/lang/String;: I4 Branch 22 IFNONNULL L209 - true
   */
  @Test
  public void test4()  throws Throwable  {
      StyleSheet styleSheet0 = StyleSheet.getInstance();
      String string0 = styleSheet0.getPrimaryKeyBackground();
      assertEquals("#bed1b8", string0);
  }

  //Test case number: 5
  /*
   * 1 covered goal:
   * 1 net.sourceforge.schemaspy.view.StyleSheet.getIndexedColumnBackground()Ljava/lang/String;: I4 Branch 23 IFNONNULL L216 - true
   */
  @Test
  public void test5()  throws Throwable  {
      StyleSheet styleSheet0 = StyleSheet.getInstance();
      String string0 = styleSheet0.getIndexedColumnBackground();
      assertEquals("#f4f7da", string0);
  }

  //Test case number: 6
  /*
   * 1 covered goal:
   * 1 net.sourceforge.schemaspy.view.StyleSheet.getSelectedTableBackground()Ljava/lang/String;: I4 Branch 24 IFNONNULL L223 - true
   */
  @Test
  public void test6()  throws Throwable  {
      StyleSheet styleSheet0 = StyleSheet.getInstance();
      String string0 = styleSheet0.getSelectedTableBackground();
      assertEquals("#a9ab96", string0);
  }

  //Test case number: 7
  /*
   * 1 covered goal:
   * 1 net.sourceforge.schemaspy.view.StyleSheet.getExcludedColumnBackgroundColor()Ljava/lang/String;: I4 Branch 25 IFNONNULL L230 - true
   */
  @Test
  public void test7()  throws Throwable  {
      StyleSheet styleSheet0 = StyleSheet.getInstance();
      String string0 = styleSheet0.getExcludedColumnBackgroundColor();
      assertEquals("#c0c0c0", string0);
  }

  //Test case number: 8
  /*
   * 1 covered goal:
   * 1 net.sourceforge.schemaspy.view.StyleSheet.getLinkColor()Ljava/lang/String;: I4 Branch 26 IFNONNULL L237 - true
   */
  @Test
  public void test8()  throws Throwable  {
      StyleSheet styleSheet0 = StyleSheet.getInstance();
      String string0 = styleSheet0.getLinkColor();
      assertEquals("#489148", string0);
  }

  //Test case number: 9
  /*
   * 2 covered goals:
   * 1 net.sourceforge.schemaspy.view.StyleSheet.getLinkVisitedColor()Ljava/lang/String;: I4 Branch 27 IFNONNULL L244 - true
   * 2 net.sourceforge.schemaspy.view.StyleSheet.getInstance()Lnet/sourceforge/schemaspy/view/StyleSheet;: I3 Branch 14 IFNONNULL L118 - true
   */
  @Test
  public void test9()  throws Throwable  {
      StyleSheet styleSheet0 = StyleSheet.getInstance();
      String string0 = styleSheet0.getLinkVisitedColor();
      assertEquals("#183118", string0);
  }
}
