/*
 * This file was automatically generated by EvoSuite
 */

package org.jsecurity.authc.credential;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import java.net.Inet4Address;
import java.net.InetAddress;
import java.net.UnknownHostException;
import org.jsecurity.authc.AuthenticationInfo;
import org.jsecurity.authc.AuthenticationToken;
import org.jsecurity.authc.SimpleAccount;
import org.jsecurity.authc.UsernamePasswordToken;
import org.jsecurity.authc.credential.SimpleCredentialsMatcher;
import org.jsecurity.subject.PrincipalCollection;
import org.jsecurity.subject.SimplePrincipalCollection;

public class SimpleCredentialsMatcherEvoSuiteTest {


  //Test case number: 0
  /*
   * 10 covered goals:
   * 1 org.jsecurity.authc.credential.SimpleCredentialsMatcher.getCredentials(Lorg/jsecurity/authc/AuthenticationInfo;)Ljava/lang/Object;: root-Branch
   * 2 org.jsecurity.authc.credential.SimpleCredentialsMatcher.doCredentialsMatch(Lorg/jsecurity/authc/AuthenticationToken;Lorg/jsecurity/authc/AuthenticationInfo;)Z: root-Branch
   * 3 org.jsecurity.authc.credential.SimpleCredentialsMatcher.getCredentials(Lorg/jsecurity/authc/AuthenticationToken;)Ljava/lang/Object;: root-Branch
   * 4 org.jsecurity.authc.credential.SimpleCredentialsMatcher.equals(Ljava/lang/Object;Ljava/lang/Object;)Z: I4 Branch 1 IFEQ L96 - true
   * 5 org.jsecurity.authc.credential.SimpleCredentialsMatcher.equals(Ljava/lang/Object;Ljava/lang/Object;)Z: I31 Branch 2 IFNE L101 - false
   * 6 org.jsecurity.authc.credential.SimpleCredentialsMatcher.equals(Ljava/lang/Object;Ljava/lang/Object;)Z: I34 Branch 3 IFNE L101 - true
   * 7 org.jsecurity.authc.credential.SimpleCredentialsMatcher.equals(Ljava/lang/Object;Ljava/lang/Object;)Z: I41 Branch 5 IFNE L101 - false
   * 8 org.jsecurity.authc.credential.SimpleCredentialsMatcher.equals(Ljava/lang/Object;Ljava/lang/Object;)Z: I44 Branch 6 IFNE L101 - false
   * 9 org.jsecurity.authc.credential.SimpleCredentialsMatcher.equals(Ljava/lang/Object;Ljava/lang/Object;)Z: I47 Branch 7 IFEQ L101 - true
   * 10 org.jsecurity.authc.credential.SimpleCredentialsMatcher.<init>()V: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      SimpleCredentialsMatcher simpleCredentialsMatcher0 = new SimpleCredentialsMatcher();
      String string0 = "f+;5bM0v\\8sp5L";
      UsernamePasswordToken usernamePasswordToken0 = new UsernamePasswordToken(string0, string0);
      SimplePrincipalCollection simplePrincipalCollection0 = new SimplePrincipalCollection();
      SimpleAccount simpleAccount0 = new SimpleAccount((PrincipalCollection) simplePrincipalCollection0, (Object) simpleCredentialsMatcher0);
      boolean boolean0 = simpleCredentialsMatcher0.doCredentialsMatch((AuthenticationToken) usernamePasswordToken0, (AuthenticationInfo) simpleAccount0);
      assertEquals(false, boolean0);
  }

  //Test case number: 1
  /*
   * 5 covered goals:
   * 1 org.jsecurity.authc.credential.SimpleCredentialsMatcher.equals(Ljava/lang/Object;Ljava/lang/Object;)Z: I34 Branch 3 IFNE L101 - false
   * 2 org.jsecurity.authc.credential.SimpleCredentialsMatcher.equals(Ljava/lang/Object;Ljava/lang/Object;)Z: I37 Branch 4 IFEQ L101 - false
   * 3 org.jsecurity.authc.credential.SimpleCredentialsMatcher.equals(Ljava/lang/Object;Ljava/lang/Object;)Z: I44 Branch 6 IFNE L101 - true
   * 4 org.jsecurity.authc.credential.SimpleCredentialsMatcher.equals(Ljava/lang/Object;Ljava/lang/Object;)Z: I52 Branch 8 IFEQ L103 - true
   * 5 org.jsecurity.authc.credential.SimpleCredentialsMatcher.getCredentials(Lorg/jsecurity/authc/AuthenticationToken;)Ljava/lang/Object;: root-Branch
   */
  @Test
  public void test1()  throws Throwable  {
      SimpleCredentialsMatcher simpleCredentialsMatcher0 = new SimpleCredentialsMatcher();
      Inet4Address inet4Address0 = (Inet4Address)InetAddress.getByName("");
      char[] charArray0 = new char[5];
      UsernamePasswordToken usernamePasswordToken0 = new UsernamePasswordToken("localhost", charArray0, false, (InetAddress) inet4Address0);
      Object object0 = simpleCredentialsMatcher0.getCredentials((AuthenticationToken) usernamePasswordToken0);
      assertNotNull(object0);
      
      boolean boolean0 = simpleCredentialsMatcher0.equals((Object) "localhost", object0);
      assertEquals(false, boolean0);
  }

  //Test case number: 2
  /*
   * 1 covered goal:
   * 1 org.jsecurity.authc.credential.SimpleCredentialsMatcher.equals(Ljava/lang/Object;Ljava/lang/Object;)Z: I37 Branch 4 IFEQ L101 - true
   */
  @Test
  public void test2()  throws Throwable  {
      SimpleCredentialsMatcher simpleCredentialsMatcher0 = new SimpleCredentialsMatcher();
      boolean boolean0 = simpleCredentialsMatcher0.equals((Object) simpleCredentialsMatcher0, (Object) simpleCredentialsMatcher0);
      assertEquals(true, boolean0);
  }

  //Test case number: 3
  /*
   * 9 covered goals:
   * 1 org.jsecurity.authc.credential.SimpleCredentialsMatcher.equals(Ljava/lang/Object;Ljava/lang/Object;)Z: I47 Branch 7 IFEQ L101 - false
   * 2 org.jsecurity.authc.credential.SimpleCredentialsMatcher.<init>()V: root-Branch
   * 3 org.jsecurity.authc.credential.SimpleCredentialsMatcher.equals(Ljava/lang/Object;Ljava/lang/Object;)Z: I4 Branch 1 IFEQ L96 - true
   * 4 org.jsecurity.authc.credential.SimpleCredentialsMatcher.equals(Ljava/lang/Object;Ljava/lang/Object;)Z: I31 Branch 2 IFNE L101 - false
   * 5 org.jsecurity.authc.credential.SimpleCredentialsMatcher.equals(Ljava/lang/Object;Ljava/lang/Object;)Z: I34 Branch 3 IFNE L101 - false
   * 6 org.jsecurity.authc.credential.SimpleCredentialsMatcher.equals(Ljava/lang/Object;Ljava/lang/Object;)Z: I37 Branch 4 IFEQ L101 - false
   * 7 org.jsecurity.authc.credential.SimpleCredentialsMatcher.equals(Ljava/lang/Object;Ljava/lang/Object;)Z: I41 Branch 5 IFNE L101 - false
   * 8 org.jsecurity.authc.credential.SimpleCredentialsMatcher.equals(Ljava/lang/Object;Ljava/lang/Object;)Z: I44 Branch 6 IFNE L101 - false
   * 9 org.jsecurity.authc.credential.SimpleCredentialsMatcher.equals(Ljava/lang/Object;Ljava/lang/Object;)Z: I52 Branch 8 IFEQ L103 - true
   */
  @Test
  public void test3()  throws Throwable  {
      SimpleCredentialsMatcher simpleCredentialsMatcher0 = new SimpleCredentialsMatcher();
      boolean boolean0 = simpleCredentialsMatcher0.equals((Object) "localhost", (Object) "localhost");
      assertEquals(true, boolean0);
  }
}
