/*
 * This file was automatically generated by EvoSuite
 */

package org.jsecurity.realm;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import java.util.Collection;
import java.util.NoSuchElementException;
import java.util.Set;
import org.jsecurity.cache.Cache;
import org.jsecurity.cache.CacheManager;
import org.jsecurity.cache.HashtableCache;
import org.jsecurity.cache.HashtableCacheManager;
import org.jsecurity.realm.SimpleAccountRealm;
import org.jsecurity.subject.PrincipalCollection;
import org.jsecurity.subject.SimplePrincipalCollection;

public class SimpleAccountRealmEvoSuiteTest {


  //Test case number: 0
  /*
   * 7 covered goals:
   * 1 org.jsecurity.realm.SimpleAccountRealm.accountExists(Ljava/lang/String;)Z: I5 Branch 2 IFNULL L85 - true
   * 2 org.jsecurity.realm.SimpleAccountRealm.afterRoleCacheSet()V: root-Branch
   * 3 org.jsecurity.realm.SimpleAccountRealm.afterAuthorizationCacheSet()V: root-Branch
   * 4 org.jsecurity.realm.SimpleAccountRealm.<init>()V: root-Branch
   * 5 org.jsecurity.realm.SimpleAccountRealm.getUser(Ljava/lang/String;)Lorg/jsecurity/authc/SimpleAccount;: root-Branch
   * 6 org.jsecurity.realm.SimpleAccountRealm.accountAndRoleCachesCreated()V: root-Branch
   * 7 org.jsecurity.realm.SimpleAccountRealm.initRoleCache()V: I4 Branch 1 IFNONNULL L72 - true
   */
  @Test
  public void test0()  throws Throwable  {
      SimpleAccountRealm simpleAccountRealm0 = new SimpleAccountRealm();
      HashtableCacheManager hashtableCacheManager0 = new HashtableCacheManager();
      simpleAccountRealm0.setCacheManager((CacheManager) hashtableCacheManager0);
      boolean boolean0 = simpleAccountRealm0.accountExists("pVk`-kKrk");
      assertEquals("org.jsecurity.realm.SimpleAccountRealm_0", simpleAccountRealm0.getName());
      assertEquals(false, boolean0);
  }

  //Test case number: 1
  /*
   * 3 covered goals:
   * 1 org.jsecurity.realm.SimpleAccountRealm.doGetAuthorizationInfo(Lorg/jsecurity/subject/PrincipalCollection;)Lorg/jsecurity/authz/AuthorizationInfo;: root-Branch
   * 2 org.jsecurity.realm.SimpleAccountRealm.<init>(Ljava/lang/String;)V: root-Branch
   * 3 org.jsecurity.realm.SimpleAccountRealm.getAuthorizationCacheKey(Lorg/jsecurity/subject/PrincipalCollection;)Ljava/lang/Object;: root-Branch
   */
  @Test
  public void test1()  throws Throwable  {
      SimpleAccountRealm simpleAccountRealm0 = new SimpleAccountRealm("UI-l:Vdk&");
      SimplePrincipalCollection simplePrincipalCollection0 = new SimplePrincipalCollection();
      // Undeclared exception!
      try {
        simpleAccountRealm0.hasAllRoles((PrincipalCollection) simplePrincipalCollection0, (Collection<String>) null);
        fail("Expecting exception: NoSuchElementException");
      } catch(NoSuchElementException e) {
      }
  }

  //Test case number: 2
  /*
   * 1 covered goal:
   * 1 org.jsecurity.realm.SimpleAccountRealm.initRoleCache()V: I4 Branch 1 IFNONNULL L72 - false
   */
  @Test
  public void test2()  throws Throwable  {
      SimpleAccountRealm simpleAccountRealm0 = new SimpleAccountRealm();
      simpleAccountRealm0.initRoleCache();
      assertEquals("org.jsecurity.realm.SimpleAccountRealm_21", simpleAccountRealm0.getName());
  }

  //Test case number: 3
  /*
   * 6 covered goals:
   * 1 org.jsecurity.realm.SimpleAccountRealm.accountExists(Ljava/lang/String;)Z: I5 Branch 2 IFNULL L85 - false
   * 2 org.jsecurity.realm.SimpleAccountRealm.addAccount(Ljava/lang/String;Ljava/lang/String;)V: root-Branch
   * 3 org.jsecurity.realm.SimpleAccountRealm.addAccount(Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)V: root-Branch
   * 4 org.jsecurity.realm.SimpleAccountRealm.getUser(Ljava/lang/String;)Lorg/jsecurity/authc/SimpleAccount;: root-Branch
   * 5 org.jsecurity.realm.SimpleAccountRealm.add(Lorg/jsecurity/authc/SimpleAccount;)V: root-Branch
   * 6 org.jsecurity.realm.SimpleAccountRealm.getAuthorizationCacheKey(Lorg/jsecurity/subject/PrincipalCollection;)Ljava/lang/Object;: root-Branch
   */
  @Test
  public void test3()  throws Throwable  {
      SimpleAccountRealm simpleAccountRealm0 = new SimpleAccountRealm();
      HashtableCache hashtableCache0 = new HashtableCache("U>dPoO#:");
      simpleAccountRealm0.setAuthorizationCache((Cache) hashtableCache0);
      simpleAccountRealm0.addAccount("U>dPoO#:", "U>dPoO#:");
      boolean boolean0 = simpleAccountRealm0.accountExists("U>dPoO#:");
      assertEquals("org.jsecurity.realm.SimpleAccountRealm_27", simpleAccountRealm0.getName());
      assertEquals(true, boolean0);
  }

  //Test case number: 4
  /*
   * 2 covered goals:
   * 1 org.jsecurity.realm.SimpleAccountRealm.roleExists(Ljava/lang/String;)Z: I5 Branch 3 IFNULL L108 - true
   * 2 org.jsecurity.realm.SimpleAccountRealm.getRole(Ljava/lang/String;)Lorg/jsecurity/authz/SimpleRole;: root-Branch
   */
  @Test
  public void test4()  throws Throwable  {
      SimpleAccountRealm simpleAccountRealm0 = new SimpleAccountRealm();
      HashtableCache hashtableCache0 = new HashtableCache("U>dPoO#:");
      simpleAccountRealm0.setAuthorizationCache((Cache) hashtableCache0);
      boolean boolean0 = simpleAccountRealm0.roleExists("U>dPoO#:");
      assertEquals("org.jsecurity.realm.SimpleAccountRealm_55", simpleAccountRealm0.getName());
      assertEquals(false, boolean0);
  }

  //Test case number: 5
  /*
   * 9 covered goals:
   * 1 org.jsecurity.realm.SimpleAccountRealm.roleExists(Ljava/lang/String;)Z: I5 Branch 3 IFNULL L108 - false
   * 2 org.jsecurity.realm.SimpleAccountRealm.afterRoleCacheSet()V: root-Branch
   * 3 org.jsecurity.realm.SimpleAccountRealm.add(Lorg/jsecurity/authz/SimpleRole;)V: root-Branch
   * 4 org.jsecurity.realm.SimpleAccountRealm.afterAuthorizationCacheSet()V: root-Branch
   * 5 org.jsecurity.realm.SimpleAccountRealm.getRole(Ljava/lang/String;)Lorg/jsecurity/authz/SimpleRole;: root-Branch
   * 6 org.jsecurity.realm.SimpleAccountRealm.<init>()V: root-Branch
   * 7 org.jsecurity.realm.SimpleAccountRealm.addRole(Ljava/lang/String;)V: root-Branch
   * 8 org.jsecurity.realm.SimpleAccountRealm.accountAndRoleCachesCreated()V: root-Branch
   * 9 org.jsecurity.realm.SimpleAccountRealm.initRoleCache()V: I4 Branch 1 IFNONNULL L72 - true
   */
  @Test
  public void test5()  throws Throwable  {
      SimpleAccountRealm simpleAccountRealm0 = new SimpleAccountRealm();
      HashtableCache hashtableCache0 = new HashtableCache("U>dPoO#:");
      simpleAccountRealm0.setAuthorizationCache((Cache) hashtableCache0);
      simpleAccountRealm0.addRole("U>dPoO#:");
      boolean boolean0 = simpleAccountRealm0.roleExists("U>dPoO#:");
      assertEquals("org.jsecurity.realm.SimpleAccountRealm_67", simpleAccountRealm0.getName());
      assertEquals(true, boolean0);
  }

  //Test case number: 6
  /*
   * 1 covered goal:
   * 1 org.jsecurity.realm.SimpleAccountRealm.toSet(Ljava/lang/String;Ljava/lang/String;)Ljava/util/Set;: I3 Branch 4 IFNULL L120 - true
   */
  @Test
  public void test6()  throws Throwable  {
      Set<String> set0 = SimpleAccountRealm.toSet((String) null, (String) null);
      assertNull(set0);
  }

  //Test case number: 7
  /*
   * 2 covered goals:
   * 1 org.jsecurity.realm.SimpleAccountRealm.toSet(Ljava/lang/String;Ljava/lang/String;)Ljava/util/Set;: I3 Branch 4 IFNULL L120 - false
   * 2 org.jsecurity.realm.SimpleAccountRealm.toSet(Ljava/lang/String;Ljava/lang/String;)Ljava/util/Set;: I8 Branch 5 IFLE L120 - false
   */
  @Test
  public void test7()  throws Throwable  {
      Set<String> set0 = SimpleAccountRealm.toSet("", "");
      assertNull(set0);
  }

  //Test case number: 8
  /*
   * 6 covered goals:
   * 1 org.jsecurity.realm.SimpleAccountRealm.toSet(Ljava/lang/String;Ljava/lang/String;)Ljava/util/Set;: I8 Branch 5 IFLE L120 - true
   * 2 org.jsecurity.realm.SimpleAccountRealm.toSet(Ljava/lang/String;Ljava/lang/String;)Ljava/util/Set;: I39 Branch 6 IF_ICMPGE L126 - true
   * 3 org.jsecurity.realm.SimpleAccountRealm.toSet(Ljava/lang/String;Ljava/lang/String;)Ljava/util/Set;: I39 Branch 6 IF_ICMPGE L126 - false
   * 4 org.jsecurity.realm.SimpleAccountRealm.toSet(Ljava/lang/String;Ljava/lang/String;)Ljava/util/Set;: I53 Branch 7 IFLE L128 - true
   * 5 org.jsecurity.realm.SimpleAccountRealm.toSet(Ljava/lang/String;Ljava/lang/String;)Ljava/util/Set;: I53 Branch 7 IFLE L128 - false
   * 6 org.jsecurity.realm.SimpleAccountRealm.toSet(Ljava/lang/String;Ljava/lang/String;)Ljava/util/Set;: I3 Branch 4 IFNULL L120 - false
   */
  @Test
  public void test8()  throws Throwable  {
      Set<String> set0 = SimpleAccountRealm.toSet("UI-l:Vck&", "");
      assertNotNull(set0);
      assertEquals(9, set0.size());
  }
}
