/*
 * This file was automatically generated by EvoSuite
 */

package org.jsecurity.authz.aop;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import java.lang.annotation.Annotation;
import org.jsecurity.authz.UnauthenticatedException;
import org.jsecurity.authz.aop.AuthenticatedAnnotationHandler;

public class AuthenticatedAnnotationHandlerEvoSuiteTest {


  //Test case number: 0
  /*
   * 2 covered goals:
   * 1 org.jsecurity.authz.aop.AuthenticatedAnnotationHandler.assertAuthorized(Ljava/lang/annotation/Annotation;)V: I4 Branch 1 IFEQ L52 - true
   * 2 org.jsecurity.authz.aop.AuthenticatedAnnotationHandler.<init>()V: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      AuthenticatedAnnotationHandler authenticatedAnnotationHandler0 = new AuthenticatedAnnotationHandler();
      authenticatedAnnotationHandler0.assertAuthorized((Annotation) null);
  }
}
