/*
 * This file was automatically generated by EvoSuite
 */

package net.sourceforge.schemaspy.util;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import net.sourceforge.schemaspy.util.DbSpecificOption;

public class DbSpecificOptionEvoSuiteTest {


  //Test case number: 0
  /*
   * 6 covered goals:
   * 1 net.sourceforge.schemaspy.util.DbSpecificOption.getValue()Ljava/lang/Object;: root-Branch
   * 2 net.sourceforge.schemaspy.util.DbSpecificOption.getName()Ljava/lang/String;: root-Branch
   * 3 net.sourceforge.schemaspy.util.DbSpecificOption.toString()Ljava/lang/String;: root-Branch
   * 4 net.sourceforge.schemaspy.util.DbSpecificOption.getDescription()Ljava/lang/String;: root-Branch
   * 5 net.sourceforge.schemaspy.util.DbSpecificOption.<init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V: root-Branch
   * 6 net.sourceforge.schemaspy.util.DbSpecificOption.<init>(Ljava/lang/String;Ljava/lang/String;)V: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      DbSpecificOption dbSpecificOption0 = new DbSpecificOption("", "");
      String string0 = dbSpecificOption0.toString();
      assertNotNull(string0);
      assertEquals("DbSpecificOption name: '' value: 'null' description: ''", string0);
  }

  //Test case number: 1
  /*
   * 3 covered goals:
   * 1 net.sourceforge.schemaspy.util.DbSpecificOption.setValue(Ljava/lang/Object;)V: root-Branch
   * 2 net.sourceforge.schemaspy.util.DbSpecificOption.<init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V: root-Branch
   * 3 net.sourceforge.schemaspy.util.DbSpecificOption.<init>(Ljava/lang/String;Ljava/lang/String;)V: root-Branch
   */
  @Test
  public void test1()  throws Throwable  {
      DbSpecificOption dbSpecificOption0 = new DbSpecificOption("", "");
      Object object0 = new Object();
      dbSpecificOption0.setValue(object0);
      assertEquals("", dbSpecificOption0.getName());
  }
}
