/*
 * This file was automatically generated by EvoSuite
 */

package net.sourceforge.schemaspy.util;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import java.lang.reflect.InvocationTargetException;
import net.sourceforge.schemaspy.util.ConsolePasswordReader;

public class ConsolePasswordReaderEvoSuiteTest {


  //Test case number: 0
  /*
   * 1 covered goal:
   * 1 net.sourceforge.schemaspy.util.ConsolePasswordReader.<init>()V: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      ConsolePasswordReader consolePasswordReader0 = null;
      try {
        consolePasswordReader0 = new ConsolePasswordReader();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
