/*
 * This file was automatically generated by EvoSuite
 */

package br.com.jnfe.base;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import br.com.jnfe.base.CST_Grupo;

public class CST_GrupoEvoSuiteTest {


  //Test case number: 0
  /*
   * 1 covered goal:
   * 1 br.com.jnfe.base.CST_Grupo.getGroup()Ljava/lang/String;: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      CST_Grupo cST_Grupo0 = CST_Grupo._10;
      String string0 = cST_Grupo0.getGroup();
      assertEquals("10", string0);
      assertNotNull(string0);
  }

  //Test case number: 1
  /*
   * 1 covered goal:
   * 1 br.com.jnfe.base.CST_Grupo.isIsento()Z: root-Branch
   */
  @Test
  public void test1()  throws Throwable  {
      CST_Grupo cST_Grupo0 = CST_Grupo._10;
      boolean boolean0 = cST_Grupo0.isIsento();
      assertEquals(false, boolean0);
  }

  //Test case number: 2
  /*
   * 1 covered goal:
   * 1 br.com.jnfe.base.CST_Grupo.isST()Z: root-Branch
   */
  @Test
  public void test2()  throws Throwable  {
      CST_Grupo cST_Grupo0 = CST_Grupo._10;
      boolean boolean0 = cST_Grupo0.isST();
      assertEquals(true, boolean0);
  }

  //Test case number: 3
  /*
   * 1 covered goal:
   * 1 br.com.jnfe.base.CST_Grupo.isSimplesNacional()Z: root-Branch
   */
  @Test
  public void test3()  throws Throwable  {
      CST_Grupo cST_Grupo0 = CST_Grupo._10;
      boolean boolean0 = cST_Grupo0.isSimplesNacional();
      assertEquals(false, boolean0);
  }

  //Test case number: 4
  /*
   * 3 covered goals:
   * 1 br.com.jnfe.base.CST_Grupo.isRequiredTag(Ljava/lang/String;)Z: I15 Branch 1 IF_ICMPGE L163 - true
   * 2 br.com.jnfe.base.CST_Grupo.isRequiredTag(Ljava/lang/String;)Z: I15 Branch 1 IF_ICMPGE L163 - false
   * 3 br.com.jnfe.base.CST_Grupo.isRequiredTag(Ljava/lang/String;)Z: I25 Branch 2 IFLE L164 - true
   */
  @Test
  public void test4()  throws Throwable  {
      CST_Grupo cST_Grupo0 = CST_Grupo._10;
      boolean boolean0 = cST_Grupo0.isRequiredTag("_10");
      assertEquals(false, boolean0);
  }

  //Test case number: 5
  /*
   * 3 covered goals:
   * 1 br.com.jnfe.base.CST_Grupo.isRequiredTag(Ljava/lang/String;)Z: I25 Branch 2 IFLE L164 - false
   * 2 br.com.jnfe.base.CST_Grupo.isRequiredTag(Ljava/lang/String;)Z: I15 Branch 1 IF_ICMPGE L163 - false
   * 3 br.com.jnfe.base.CST_Grupo.isRequiredTag(Ljava/lang/String;)Z: I25 Branch 2 IFLE L164 - true
   */
  @Test
  public void test5()  throws Throwable  {
      CST_Grupo cST_Grupo0 = CST_Grupo._SN500;
      boolean boolean0 = cST_Grupo0.isRequiredTag("vICMSSTRet");
      assertEquals(true, boolean0);
  }
}
