/*
 * This file was automatically generated by EvoSuite
 */

package br.com.jnfe.base;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import br.com.jnfe.base.IndPag;

public class IndPagEvoSuiteTest {


  //Test case number: 0
  /*
   * 1 covered goal:
   * 1 br.com.jnfe.base.IndPag.getValue()C: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      IndPag indPag0 = IndPag.PGTO_A_VISTA;
      char char0 = indPag0.getValue();
      assertEquals('0', char0);
  }
}
