/*
 * This file was automatically generated by EvoSuite
 */

package br.com.jnfe.base;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import br.com.jnfe.base.RegimeEspecialTributario;

public class RegimeEspecialTributarioEvoSuiteTest {


  //Test case number: 0
  /*
   * 1 covered goal:
   * 1 br.com.jnfe.base.RegimeEspecialTributario.getValue()C: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      RegimeEspecialTributario regimeEspecialTributario0 = RegimeEspecialTributario.MICROEMPRESA_PEQUENO_PORTE;
      char char0 = regimeEspecialTributario0.getValue();
      assertEquals('6', char0);
  }
}
