/*
 * This file was automatically generated by EvoSuite
 */

package br.com.jnfe.base;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import br.com.jnfe.base.TpAmb;

public class TpAmbEvoSuiteTest {


  //Test case number: 0
  /*
   * 1 covered goal:
   * 1 br.com.jnfe.base.TpAmb.getValueAsString()Ljava/lang/String;: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      TpAmb tpAmb0 = TpAmb.PRODUCAO;
      String string0 = tpAmb0.getValueAsString();
      assertEquals("1", string0);
      assertNotNull(string0);
  }

  //Test case number: 1
  /*
   * 1 covered goal:
   * 1 br.com.jnfe.base.TpAmb.getValue()C: root-Branch
   */
  @Test
  public void test1()  throws Throwable  {
      TpAmb tpAmb0 = TpAmb.PRODUCAO;
      char char0 = tpAmb0.getValue();
      assertEquals('1', char0);
  }
}
