/*
 * This file was automatically generated by EvoSuite
 */

package br.com.jnfe.base;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import br.com.jnfe.base.TpObsNFe;

public class TpObsNFeEvoSuiteTest {


  //Test case number: 0
  /*
   * 1 covered goal:
   * 1 br.com.jnfe.base.TpObsNFe.getValue()C: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      TpObsNFe tpObsNFe0 = TpObsNFe.FISCO;
      char char0 = tpObsNFe0.getValue();
      assertEquals('F', char0);
  }
}
