/*
 * This file was automatically generated by EvoSuite
 */

package br.com.jnfe.base;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import br.com.jnfe.base.TpVeiculo;

public class TpVeiculoEvoSuiteTest {


  //Test case number: 0
  /*
   * 1 covered goal:
   * 1 br.com.jnfe.base.TpVeiculo.getValue()C: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      TpVeiculo tpVeiculo0 = TpVeiculo.VEICULO;
      char char0 = tpVeiculo0.getValue();
      assertEquals('V', char0);
  }
}
