/*
 * This file was automatically generated by EvoSuite
 */

package net.sourceforge.schemaspy.view;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import net.sourceforge.schemaspy.util.Dot;
import net.sourceforge.schemaspy.view.HtmlDiagramFormatter;

public class HtmlDiagramFormatterEvoSuiteTest {


  //Test case number: 0
  /*
   * 3 covered goals:
   * 1 net.sourceforge.schemaspy.view.HtmlDiagramFormatter.getDot()Lnet/sourceforge/schemaspy/util/Dot;: I8 Branch 1 IFNE L32 - false
   * 2 net.sourceforge.schemaspy.view.HtmlDiagramFormatter.getDot()Lnet/sourceforge/schemaspy/util/Dot;: I12 Branch 2 IFNE L33 - true
   * 3 net.sourceforge.schemaspy.view.HtmlDiagramFormatter.<init>()V: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      HtmlDiagramFormatter htmlDiagramFormatter0 = new HtmlDiagramFormatter();
      Dot dot0 = htmlDiagramFormatter0.getDot();
      assertNull(dot0);
  }
}
