/*
 * This file was automatically generated by EvoSuite
 */

package br.com.jnfe.base.adapter.dom;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;

public class AbstractNFeDOMAdapterEvoSuiteTest {

}
