/*
 * This file was automatically generated by EvoSuite
 */

package nu.staldal.lagoon;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;

public class YesNoQueryDialogEvoSuiteTest {

}
