/*
 * This file was automatically generated by EvoSuite
 */

package net.sf.jniinchi;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import java.util.LinkedList;
import java.util.List;
import net.sf.jniinchi.JniInchiException;
import net.sf.jniinchi.JniInchiInput;
import net.sf.jniinchi.JniInchiStructure;

public class JniInchiInputEvoSuiteTest {


  //Test case number: 0
  /*
   * 2 covered goals:
   * 1 net.sf.jniinchi.JniInchiInput.<init>(Lnet/sf/jniinchi/JniInchiStructure;)V: root-Branch
   * 2 net.sf.jniinchi.JniInchiInput.<init>()V: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      JniInchiInput jniInchiInput0 = new JniInchiInput();
      JniInchiInput jniInchiInput1 = new JniInchiInput((JniInchiStructure) jniInchiInput0);
      assertNotSame(jniInchiInput0, jniInchiInput1);
  }

  //Test case number: 1
  /*
   * 2 covered goals:
   * 1 net.sf.jniinchi.JniInchiInput.<init>(Lnet/sf/jniinchi/JniInchiStructure;Ljava/lang/String;)V: root-Branch
   * 2 net.sf.jniinchi.JniInchiInput.<init>(Ljava/lang/String;)V: I8 Branch 1 IFNONNULL L48 - false
   */
  @Test
  public void test1()  throws Throwable  {
      JniInchiInput jniInchiInput0 = null;
      try {
        jniInchiInput0 = new JniInchiInput((JniInchiStructure) null, (String) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  //Test case number: 2
  /*
   * 1 covered goal:
   * 1 net.sf.jniinchi.JniInchiInput.getOptions()Ljava/lang/String;: root-Branch
   */
  @Test
  public void test2()  throws Throwable  {
      JniInchiInput jniInchiInput0 = new JniInchiInput();
      String string0 = jniInchiInput0.getOptions();
      assertEquals("", string0);
  }

  //Test case number: 3
  /*
   * 1 covered goal:
   * 1 net.sf.jniinchi.JniInchiInput.<init>(Ljava/util/List;)V: root-Branch
   */
  @Test
  public void test3()  throws Throwable  {
      LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
      JniInchiInput jniInchiInput0 = null;
      try {
        jniInchiInput0 = new JniInchiInput((List) linkedList0);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * net/sf/jnati/NativeCodeException
         */
      }
  }

  //Test case number: 4
  /*
   * 2 covered goals:
   * 1 net.sf.jniinchi.JniInchiInput.<init>(Ljava/lang/String;)V: I8 Branch 1 IFNONNULL L48 - true
   * 2 net.sf.jniinchi.JniInchiInput.<init>()V: root-Branch
   */
  @Test
  public void test4()  throws Throwable  {
      JniInchiInput jniInchiInput0 = new JniInchiInput();
      JniInchiInput jniInchiInput1 = null;
      try {
        jniInchiInput1 = new JniInchiInput((JniInchiStructure) jniInchiInput0, "");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * net/sf/jnati/NativeCodeException
         */
      }
  }
}
