/*
 * This file was automatically generated by EvoSuite
 */

package nu.staldal.util;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import nu.staldal.util.Utils;

public class UtilsEvoSuiteTest {


  //Test case number: 0
  /*
   * 16 covered goals:
   * 1 nu.staldal.util.Utils.encodePath(Ljava/lang/String;)Ljava/lang/String;: I26 Branch 2 LOOKUPSWITCH L67 Case 36 - true
   * 2 nu.staldal.util.Utils.encodePath(Ljava/lang/String;)Ljava/lang/String;: I26 Branch 3 LOOKUPSWITCH L67 Case 42 - true
   * 3 nu.staldal.util.Utils.encodePath(Ljava/lang/String;)Ljava/lang/String;: I26 Branch 7 LOOKUPSWITCH L67 Case 63 - true
   * 4 nu.staldal.util.Utils.encodePath(Ljava/lang/String;)Ljava/lang/String;: I26 Branch 11 LOOKUPSWITCH L67 Default-Case - false
   * 5 nu.staldal.util.Utils.encodePath(Ljava/lang/String;)Ljava/lang/String;: I16 Branch 1 IF_ICMPGE L64 - true
   * 6 nu.staldal.util.Utils.encodePath(Ljava/lang/String;)Ljava/lang/String;: I16 Branch 1 IF_ICMPGE L64 - false
   * 7 nu.staldal.util.Utils.encodePath(Ljava/lang/String;)Ljava/lang/String;: I26 Branch 2 LOOKUPSWITCH L67 Case 36 - false
   * 8 nu.staldal.util.Utils.encodePath(Ljava/lang/String;)Ljava/lang/String;: I26 Branch 3 LOOKUPSWITCH L67 Case 42 - false
   * 9 nu.staldal.util.Utils.encodePath(Ljava/lang/String;)Ljava/lang/String;: I26 Branch 4 LOOKUPSWITCH L67 Case 45 - false
   * 10 nu.staldal.util.Utils.encodePath(Ljava/lang/String;)Ljava/lang/String;: I26 Branch 5 LOOKUPSWITCH L67 Case 47 - false
   * 11 nu.staldal.util.Utils.encodePath(Ljava/lang/String;)Ljava/lang/String;: I26 Branch 6 LOOKUPSWITCH L67 Case 58 - false
   * 12 nu.staldal.util.Utils.encodePath(Ljava/lang/String;)Ljava/lang/String;: I26 Branch 7 LOOKUPSWITCH L67 Case 63 - false
   * 13 nu.staldal.util.Utils.encodePath(Ljava/lang/String;)Ljava/lang/String;: I26 Branch 8 LOOKUPSWITCH L67 Case 92 - false
   * 14 nu.staldal.util.Utils.encodePath(Ljava/lang/String;)Ljava/lang/String;: I26 Branch 9 LOOKUPSWITCH L67 Case 95 - false
   * 15 nu.staldal.util.Utils.encodePath(Ljava/lang/String;)Ljava/lang/String;: I26 Branch 10 LOOKUPSWITCH L67 Case 126 - false
   * 16 nu.staldal.util.Utils.encodePath(Ljava/lang/String;)Ljava/lang/String;: I26 Branch 11 LOOKUPSWITCH L67 Default-Case - true
   */
  @Test
  public void test0()  throws Throwable  {
      String string0 = Utils.encodePath("S4i*?8oL]6^p)uten$");
      assertNotNull(string0);
      assertEquals("S4i_$8oL]6^p)uten$$", string0);
  }

  //Test case number: 1
  /*
   * 1 covered goal:
   * 1 nu.staldal.util.Utils.encodePath(Ljava/lang/String;)Ljava/lang/String;: I26 Branch 4 LOOKUPSWITCH L67 Case 45 - true
   */
  @Test
  public void test1()  throws Throwable  {
      String string0 = Utils.encodePath("--");
      assertEquals("----", string0);
      assertNotNull(string0);
  }

  //Test case number: 2
  /*
   * 1 covered goal:
   * 1 nu.staldal.util.Utils.encodePath(Ljava/lang/String;)Ljava/lang/String;: I26 Branch 5 LOOKUPSWITCH L67 Case 47 - true
   */
  @Test
  public void test2()  throws Throwable  {
      String string0 = Utils.encodePath("/#");
      assertNotNull(string0);
      assertEquals("-#", string0);
  }

  //Test case number: 3
  /*
   * 2 covered goals:
   * 1 nu.staldal.util.Utils.encodePath(Ljava/lang/String;)Ljava/lang/String;: I26 Branch 6 LOOKUPSWITCH L67 Case 58 - true
   * 2 nu.staldal.util.Utils.encodePath(Ljava/lang/String;)Ljava/lang/String;: I26 Branch 3 LOOKUPSWITCH L67 Case 42 - true
   */
  @Test
  public void test3()  throws Throwable  {
      String string0 = Utils.encodePath("l`z2vE%D!yk:J'v*2C9");
      assertEquals("l`z2vE%D!yk~J'v_2C9", string0);
      assertNotNull(string0);
  }

  //Test case number: 4
  /*
   * 1 covered goal:
   * 1 nu.staldal.util.Utils.encodePath(Ljava/lang/String;)Ljava/lang/String;: I26 Branch 9 LOOKUPSWITCH L67 Case 95 - true
   */
  @Test
  public void test4()  throws Throwable  {
      String string0 = Utils.encodePath("&xxbi[(_eO8");
      assertNotNull(string0);
      assertEquals("&xxbi[(__eO8", string0);
  }

  //Test case number: 5
  /*
   * 14 covered goals:
   * 1 nu.staldal.util.Utils.encodePath(Ljava/lang/String;)Ljava/lang/String;: I26 Branch 10 LOOKUPSWITCH L67 Case 126 - true
   * 2 nu.staldal.util.Utils.encodePath(Ljava/lang/String;)Ljava/lang/String;: I16 Branch 1 IF_ICMPGE L64 - true
   * 3 nu.staldal.util.Utils.encodePath(Ljava/lang/String;)Ljava/lang/String;: I16 Branch 1 IF_ICMPGE L64 - false
   * 4 nu.staldal.util.Utils.encodePath(Ljava/lang/String;)Ljava/lang/String;: I26 Branch 2 LOOKUPSWITCH L67 Case 36 - false
   * 5 nu.staldal.util.Utils.encodePath(Ljava/lang/String;)Ljava/lang/String;: I26 Branch 3 LOOKUPSWITCH L67 Case 42 - false
   * 6 nu.staldal.util.Utils.encodePath(Ljava/lang/String;)Ljava/lang/String;: I26 Branch 4 LOOKUPSWITCH L67 Case 45 - false
   * 7 nu.staldal.util.Utils.encodePath(Ljava/lang/String;)Ljava/lang/String;: I26 Branch 5 LOOKUPSWITCH L67 Case 47 - false
   * 8 nu.staldal.util.Utils.encodePath(Ljava/lang/String;)Ljava/lang/String;: I26 Branch 6 LOOKUPSWITCH L67 Case 58 - false
   * 9 nu.staldal.util.Utils.encodePath(Ljava/lang/String;)Ljava/lang/String;: I26 Branch 7 LOOKUPSWITCH L67 Case 63 - false
   * 10 nu.staldal.util.Utils.encodePath(Ljava/lang/String;)Ljava/lang/String;: I26 Branch 8 LOOKUPSWITCH L67 Case 92 - false
   * 11 nu.staldal.util.Utils.encodePath(Ljava/lang/String;)Ljava/lang/String;: I26 Branch 9 LOOKUPSWITCH L67 Case 95 - false
   * 12 nu.staldal.util.Utils.encodePath(Ljava/lang/String;)Ljava/lang/String;: I26 Branch 10 LOOKUPSWITCH L67 Case 126 - false
   * 13 nu.staldal.util.Utils.encodePath(Ljava/lang/String;)Ljava/lang/String;: I26 Branch 11 LOOKUPSWITCH L67 Default-Case - true
   * 14 nu.staldal.util.Utils.encodePath(Ljava/lang/String;)Ljava/lang/String;: I26 Branch 11 LOOKUPSWITCH L67 Default-Case - false
   */
  @Test
  public void test5()  throws Throwable  {
      String string0 = Utils.encodePath("]4iZ@L}.~O");
      assertEquals("]4iZ@L}.~~O", string0);
      assertNotNull(string0);
  }

  //Test case number: 6
  /*
   * 5 covered goals:
   * 1 nu.staldal.util.Utils.encodePathAsIdentifier(Ljava/lang/String;)Ljava/lang/String;: I18 Branch 12 IFEQ L116 - true
   * 2 nu.staldal.util.Utils.encodePathAsIdentifier(Ljava/lang/String;)Ljava/lang/String;: I49 Branch 13 IF_ICMPGE L121 - true
   * 3 nu.staldal.util.Utils.encodePathAsIdentifier(Ljava/lang/String;)Ljava/lang/String;: I49 Branch 13 IF_ICMPGE L121 - false
   * 4 nu.staldal.util.Utils.encodePathAsIdentifier(Ljava/lang/String;)Ljava/lang/String;: I60 Branch 14 IFEQ L124 - true
   * 5 nu.staldal.util.Utils.encodePathAsIdentifier(Ljava/lang/String;)Ljava/lang/String;: I60 Branch 14 IFEQ L124 - false
   */
  @Test
  public void test6()  throws Throwable  {
      String string0 = Utils.encodePathAsIdentifier("478Ev7rh`");
      assertNotNull(string0);
      assertEquals("_52_78Ev7rh_96_", string0);
  }

  //Test case number: 7
  /*
   * 4 covered goals:
   * 1 nu.staldal.util.Utils.encodePathAsIdentifier(Ljava/lang/String;)Ljava/lang/String;: I18 Branch 12 IFEQ L116 - false
   * 2 nu.staldal.util.Utils.encodePathAsIdentifier(Ljava/lang/String;)Ljava/lang/String;: I49 Branch 13 IF_ICMPGE L121 - true
   * 3 nu.staldal.util.Utils.encodePathAsIdentifier(Ljava/lang/String;)Ljava/lang/String;: I49 Branch 13 IF_ICMPGE L121 - false
   * 4 nu.staldal.util.Utils.encodePathAsIdentifier(Ljava/lang/String;)Ljava/lang/String;: I60 Branch 14 IFEQ L124 - false
   */
  @Test
  public void test7()  throws Throwable  {
      String string0 = Utils.encodePathAsIdentifier("_45_eE_62_y_34__44_SZ2_59_");
      assertNotNull(string0);
      assertEquals("_45_eE_62_y_34__44_SZ2_59_", string0);
  }

  //Test case number: 8
  /*
   * 3 covered goals:
   * 1 nu.staldal.util.Utils.absoluteURL(Ljava/lang/String;)Z: I9 Branch 15 IFGE L143 - true
   * 2 nu.staldal.util.Utils.absoluteURL(Ljava/lang/String;)Z: I21 Branch 16 IFGE L146 - true
   * 3 nu.staldal.util.Utils.absoluteURL(Ljava/lang/String;)Z: I28 Branch 17 IF_ICMPGE L148 - true
   */
  @Test
  public void test8()  throws Throwable  {
      boolean boolean0 = Utils.absoluteURL("ng^/GJX?`'M3}:");
      assertEquals(false, boolean0);
  }

  //Test case number: 9
  /*
   * 1 covered goal:
   * 1 nu.staldal.util.Utils.absoluteURL(Ljava/lang/String;)Z: I9 Branch 15 IFGE L143 - false
   */
  @Test
  public void test9()  throws Throwable  {
      boolean boolean0 = Utils.absoluteURL("i@=&qd #}5;>@ s");
      assertEquals(false, boolean0);
  }

  //Test case number: 10
  /*
   * 1 covered goal:
   * 1 nu.staldal.util.Utils.absoluteURL(Ljava/lang/String;)Z: I21 Branch 16 IFGE L146 - false
   */
  @Test
  public void test10()  throws Throwable  {
      boolean boolean0 = Utils.absoluteURL("l`z2vE%D!yk:J'v*2C9");
      assertEquals(true, boolean0);
  }

  //Test case number: 11
  /*
   * 3 covered goals:
   * 1 nu.staldal.util.Utils.absoluteURL(Ljava/lang/String;)Z: I28 Branch 17 IF_ICMPGE L148 - false
   * 2 nu.staldal.util.Utils.absoluteURL(Ljava/lang/String;)Z: I9 Branch 15 IFGE L143 - true
   * 3 nu.staldal.util.Utils.absoluteURL(Ljava/lang/String;)Z: I21 Branch 16 IFGE L146 - true
   */
  @Test
  public void test11()  throws Throwable  {
      boolean boolean0 = Utils.absoluteURL("}\f:7/$`~R21Y|");
      assertEquals(true, boolean0);
  }

  //Test case number: 12
  /*
   * 1 covered goal:
   * 1 nu.staldal.util.Utils.pseudoAbsoluteURL(Ljava/lang/String;)Z: I4 Branch 18 IFLE L158 - true
   */
  @Test
  public void test12()  throws Throwable  {
      boolean boolean0 = Utils.pseudoAbsoluteURL("");
      assertEquals(false, boolean0);
  }

  //Test case number: 13
  /*
   * 2 covered goals:
   * 1 nu.staldal.util.Utils.pseudoAbsoluteURL(Ljava/lang/String;)Z: I4 Branch 18 IFLE L158 - false
   * 2 nu.staldal.util.Utils.pseudoAbsoluteURL(Ljava/lang/String;)Z: I9 Branch 19 IF_ICMPNE L158 - true
   */
  @Test
  public void test13()  throws Throwable  {
      boolean boolean0 = Utils.pseudoAbsoluteURL("478Ev7rh`");
      assertEquals(false, boolean0);
  }

  //Test case number: 14
  /*
   * 2 covered goals:
   * 1 nu.staldal.util.Utils.pseudoAbsoluteURL(Ljava/lang/String;)Z: I9 Branch 19 IF_ICMPNE L158 - false
   * 2 nu.staldal.util.Utils.pseudoAbsoluteURL(Ljava/lang/String;)Z: I4 Branch 18 IFLE L158 - false
   */
  @Test
  public void test14()  throws Throwable  {
      boolean boolean0 = Utils.pseudoAbsoluteURL("/#");
      assertEquals(true, boolean0);
  }

  //Test case number: 15
  /*
   * 2 covered goals:
   * 1 nu.staldal.util.Utils.nChars(IC)Ljava/lang/String;: I14 Branch 20 IF_ICMPGE L169 - true
   * 2 nu.staldal.util.Utils.nChars(IC)Ljava/lang/String;: I14 Branch 20 IF_ICMPGE L169 - false
   */
  @Test
  public void test15()  throws Throwable  {
      String string0 = Utils.nChars((int) '', 'a');
      assertNotNull(string0);
      assertEquals("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", string0);
  }
}
