/*
 * This file was automatically generated by EvoSuite
 */

package net.sf.xisemele.impl;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import net.sf.xisemele.impl.ElementImpl;
import net.sf.xisemele.impl.Factory;
import org.w3c.dom.Node;

public class ElementImplEvoSuiteTest {
}
