/*
 * This file was automatically generated by EvoSuite
 */

package net.sf.xisemele.impl;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import net.sf.xisemele.impl.Factory;
import net.sf.xisemele.impl.FormatterProvider;
import net.sf.xisemele.impl.WriterEditorImpl;
import org.w3c.dom.Document;

public class WriterEditorImplEvoSuiteTest {
}
