/*
 * This file was automatically generated by EvoSuite
 */

package nu.staldal.lagoon;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import java.io.File;
import nu.staldal.lagoon.BuildSitemap;
import org.xml.sax.ContentHandler;
import org.xml.sax.SAXException;

public class BuildSitemapEvoSuiteTest {


  //Test case number: 0
  /*
   * 1 covered goal:
   * 1 nu.staldal.lagoon.BuildSitemap.<init>()V: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      BuildSitemap buildSitemap0 = new BuildSitemap();
      assertNotNull(buildSitemap0);
  }

  //Test case number: 1
  /*
   * 1 covered goal:
   * 1 nu.staldal.lagoon.BuildSitemap.processDirectory(Ljava/io/File;Lorg/xml/sax/ContentHandler;)V: I3 Branch 1 IFNONNULL L108 - false
   */
  @Test
  public void test1()  throws Throwable  {
      // Undeclared exception!
      try {
        BuildSitemap.processDirectory((File) null, (ContentHandler) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
