/*
 * This file was automatically generated by EvoSuite
 */

package org.databene.jdbacl;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import java.io.IOException;
import org.databene.jdbacl.JDBCConnectData;

public class JDBCConnectDataEvoSuiteTest {


  //Test case number: 0
  /*
   * 2 covered goals:
   * 1 org.databene.jdbacl.JDBCConnectData.<init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V: root-Branch
   * 2 org.databene.jdbacl.JDBCConnectData.<init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      JDBCConnectData jDBCConnectData0 = new JDBCConnectData("", "", "{UdEN!2T|mka=2!$[", "{UdEN!2T|mka=2!$[");
      assertNotNull(jDBCConnectData0);
  }

  //Test case number: 1
  /*
   * 1 covered goal:
   * 1 org.databene.jdbacl.JDBCConnectData.parseSingleDbProperties(Ljava/lang/String;)Lorg/databene/jdbacl/JDBCConnectData;: root-Branch
   */
  @Test
  public void test1()  throws Throwable  {
      // Undeclared exception!
      try {
        JDBCConnectData.parseSingleDbProperties("db_password");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * org/databene/commons/IOUtil
         */
      }
  }
}
