/*
 * This file was automatically generated by EvoSuite
 */

package nu.staldal.xmlutil;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import java.io.ByteArrayOutputStream;
import java.io.OutputStream;
import java.io.PipedOutputStream;
import java.io.PrintWriter;
import java.io.StringWriter;
import java.io.Writer;
import nu.staldal.xmlutil.ContentHandlerSnooper;
import org.xml.sax.Attributes;
import org.xml.sax.ContentHandler;
import org.xml.sax.Locator;
import org.xml.sax.SAXException;
import org.xml.sax.ext.Attributes2Impl;
import org.xml.sax.ext.DefaultHandler2;
import org.xml.sax.helpers.DefaultHandler;
import org.xml.sax.helpers.LocatorImpl;
import org.xml.sax.helpers.XMLFilterImpl;

public class ContentHandlerSnooperEvoSuiteTest {


  //Test case number: 0
  /*
   * 2 covered goals:
   * 1 nu.staldal.xmlutil.ContentHandlerSnooper.skippedEntity(Ljava/lang/String;)V: root-Branch
   * 2 nu.staldal.xmlutil.ContentHandlerSnooper.<init>(Lorg/xml/sax/ContentHandler;Ljava/io/PrintWriter;)V: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      DefaultHandler defaultHandler0 = new DefaultHandler();
      PipedOutputStream pipedOutputStream0 = new PipedOutputStream();
      PrintWriter printWriter0 = new PrintWriter((OutputStream) pipedOutputStream0, true);
      ContentHandlerSnooper contentHandlerSnooper0 = new ContentHandlerSnooper((ContentHandler) defaultHandler0, printWriter0);
      contentHandlerSnooper0.skippedEntity("");
  }

  //Test case number: 1
  /*
   * 1 covered goal:
   * 1 nu.staldal.xmlutil.ContentHandlerSnooper.processingInstruction(Ljava/lang/String;Ljava/lang/String;)V: root-Branch
   */
  @Test
  public void test1()  throws Throwable  {
      DefaultHandler defaultHandler0 = new DefaultHandler();
      PipedOutputStream pipedOutputStream0 = new PipedOutputStream();
      PrintWriter printWriter0 = new PrintWriter((OutputStream) pipedOutputStream0, true);
      ContentHandlerSnooper contentHandlerSnooper0 = new ContentHandlerSnooper((ContentHandler) defaultHandler0, printWriter0);
      contentHandlerSnooper0.processingInstruction("", "");
  }

  //Test case number: 2
  /*
   * 1 covered goal:
   * 1 nu.staldal.xmlutil.ContentHandlerSnooper.ignorableWhitespace([CII)V: root-Branch
   */
  @Test
  public void test2()  throws Throwable  {
      DefaultHandler defaultHandler0 = new DefaultHandler();
      PipedOutputStream pipedOutputStream0 = new PipedOutputStream();
      PrintWriter printWriter0 = new PrintWriter((OutputStream) pipedOutputStream0, true);
      ContentHandlerSnooper contentHandlerSnooper0 = new ContentHandlerSnooper((ContentHandler) defaultHandler0, printWriter0);
      char[] charArray0 = new char[1];
      contentHandlerSnooper0.ignorableWhitespace(charArray0, (int) ',', (-258));
  }

  //Test case number: 3
  /*
   * 1 covered goal:
   * 1 nu.staldal.xmlutil.ContentHandlerSnooper.endDocument()V: root-Branch
   */
  @Test
  public void test3()  throws Throwable  {
      DefaultHandler defaultHandler0 = new DefaultHandler();
      PipedOutputStream pipedOutputStream0 = new PipedOutputStream();
      PrintWriter printWriter0 = new PrintWriter((OutputStream) pipedOutputStream0, true);
      ContentHandlerSnooper contentHandlerSnooper0 = new ContentHandlerSnooper((ContentHandler) defaultHandler0, printWriter0);
      contentHandlerSnooper0.endDocument();
  }

  //Test case number: 4
  /*
   * 1 covered goal:
   * 1 nu.staldal.xmlutil.ContentHandlerSnooper.setDocumentLocator(Lorg/xml/sax/Locator;)V: root-Branch
   */
  @Test
  public void test4()  throws Throwable  {
      DefaultHandler defaultHandler0 = new DefaultHandler();
      PipedOutputStream pipedOutputStream0 = new PipedOutputStream();
      PrintWriter printWriter0 = new PrintWriter((OutputStream) pipedOutputStream0, true);
      ContentHandlerSnooper contentHandlerSnooper0 = new ContentHandlerSnooper((ContentHandler) defaultHandler0, printWriter0);
      LocatorImpl locatorImpl0 = new LocatorImpl();
      contentHandlerSnooper0.setDocumentLocator((Locator) locatorImpl0);
      assertEquals(true, printWriter0.checkError());
  }

  //Test case number: 5
  /*
   * 1 covered goal:
   * 1 nu.staldal.xmlutil.ContentHandlerSnooper.startDocument()V: root-Branch
   */
  @Test
  public void test5()  throws Throwable  {
      DefaultHandler defaultHandler0 = new DefaultHandler();
      PipedOutputStream pipedOutputStream0 = new PipedOutputStream();
      PrintWriter printWriter0 = new PrintWriter((OutputStream) pipedOutputStream0, true);
      ContentHandlerSnooper contentHandlerSnooper0 = new ContentHandlerSnooper((ContentHandler) defaultHandler0, printWriter0);
      contentHandlerSnooper0.startDocument();
  }

  //Test case number: 6
  /*
   * 1 covered goal:
   * 1 nu.staldal.xmlutil.ContentHandlerSnooper.endElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V: root-Branch
   */
  @Test
  public void test6()  throws Throwable  {
      DefaultHandler2 defaultHandler2_0 = new DefaultHandler2();
      StringWriter stringWriter0 = new StringWriter();
      PrintWriter printWriter0 = new PrintWriter((Writer) stringWriter0, true);
      ContentHandlerSnooper contentHandlerSnooper0 = new ContentHandlerSnooper((ContentHandler) defaultHandler2_0, printWriter0);
      contentHandlerSnooper0.endElement("xlN[R=x", "xlN[R=x", "xlN[R=x");
      assertEquals("New ContentHandlerSnooper\nendElement(xlN[R=x,xlN[R=x,xlN[R=x)\n", stringWriter0.toString());
  }

  //Test case number: 7
  /*
   * 1 covered goal:
   * 1 nu.staldal.xmlutil.ContentHandlerSnooper.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: root-Branch
   */
  @Test
  public void test7()  throws Throwable  {
      DefaultHandler defaultHandler0 = new DefaultHandler();
      PipedOutputStream pipedOutputStream0 = new PipedOutputStream();
      PrintWriter printWriter0 = new PrintWriter((OutputStream) pipedOutputStream0, true);
      ContentHandlerSnooper contentHandlerSnooper0 = new ContentHandlerSnooper((ContentHandler) defaultHandler0, printWriter0);
      Attributes2Impl attributes2Impl0 = new Attributes2Impl();
      contentHandlerSnooper0.startElement("", "", "", (Attributes) attributes2Impl0);
      assertEquals(0, attributes2Impl0.getLength());
  }

  //Test case number: 8
  /*
   * 1 covered goal:
   * 1 nu.staldal.xmlutil.ContentHandlerSnooper.characters([CII)V: root-Branch
   */
  @Test
  public void test8()  throws Throwable  {
      XMLFilterImpl xMLFilterImpl0 = new XMLFilterImpl();
      ByteArrayOutputStream byteArrayOutputStream0 = new ByteArrayOutputStream();
      PrintWriter printWriter0 = new PrintWriter((OutputStream) byteArrayOutputStream0);
      ContentHandlerSnooper contentHandlerSnooper0 = new ContentHandlerSnooper((ContentHandler) xMLFilterImpl0, printWriter0);
      char[] charArray0 = new char[7];
      contentHandlerSnooper0.characters(charArray0, (-1735), (-358));
      assertEquals("New ContentHandlerSnooper\ncharacters\n", byteArrayOutputStream0.toString());
      assertEquals(37, byteArrayOutputStream0.size());
  }

  //Test case number: 9
  /*
   * 1 covered goal:
   * 1 nu.staldal.xmlutil.ContentHandlerSnooper.startPrefixMapping(Ljava/lang/String;Ljava/lang/String;)V: I11 Branch 1 IFNE L121 - false
   */
  @Test
  public void test9()  throws Throwable  {
      DefaultHandler defaultHandler0 = new DefaultHandler();
      PipedOutputStream pipedOutputStream0 = new PipedOutputStream();
      PrintWriter printWriter0 = new PrintWriter((OutputStream) pipedOutputStream0, true);
      ContentHandlerSnooper contentHandlerSnooper0 = new ContentHandlerSnooper((ContentHandler) defaultHandler0, printWriter0);
      contentHandlerSnooper0.startPrefixMapping("", "");
  }

  //Test case number: 10
  /*
   * 2 covered goals:
   * 1 nu.staldal.xmlutil.ContentHandlerSnooper.endPrefixMapping(Ljava/lang/String;)V: I11 Branch 2 IFNE L130 - false
   * 2 nu.staldal.xmlutil.ContentHandlerSnooper.<init>(Lorg/xml/sax/ContentHandler;Ljava/io/PrintWriter;)V: root-Branch
   */
  @Test
  public void test10()  throws Throwable  {
      DefaultHandler defaultHandler0 = new DefaultHandler();
      PipedOutputStream pipedOutputStream0 = new PipedOutputStream();
      PrintWriter printWriter0 = new PrintWriter((OutputStream) pipedOutputStream0, true);
      ContentHandlerSnooper contentHandlerSnooper0 = new ContentHandlerSnooper((ContentHandler) defaultHandler0, printWriter0);
      contentHandlerSnooper0.endPrefixMapping("");
  }
}
