/*
 * This file was automatically generated by EvoSuite
 */

package nu.staldal.xmlutil;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;

public class XMLReaderImplEvoSuiteTest {

}
