/*
 * This file was automatically generated by EvoSuite
 */

package nu.staldal.lagoon.producer;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import java.io.IOException;
import nu.staldal.lagoon.core.LagoonException;
import nu.staldal.lagoon.core.Target;
import nu.staldal.lagoon.producer.LSSITransformer;
import org.xml.sax.ContentHandler;
import org.xml.sax.SAXException;
import org.xml.sax.helpers.XMLFilterImpl;

public class LSSITransformerEvoSuiteTest {


  //Test case number: 0
  /*
   * 2 covered goals:
   * 1 nu.staldal.lagoon.producer.LSSITransformer.init()V: root-Branch
   * 2 nu.staldal.lagoon.producer.LSSITransformer.<init>()V: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      LSSITransformer lSSITransformer0 = new LSSITransformer();
      lSSITransformer0.init();
      assertEquals(0, lSSITransformer0.getPosition());
  }

  //Test case number: 1
  /*
   * 2 covered goals:
   * 1 nu.staldal.lagoon.producer.LSSITransformer.start(Lorg/xml/sax/ContentHandler;Lnu/staldal/lagoon/core/Target;)V: root-Branch
   * 2 nu.staldal.lagoon.producer.LSSITransformer.<init>()V: root-Branch
   */
  @Test
  public void test1()  throws Throwable  {
      LSSITransformer lSSITransformer0 = new LSSITransformer();
      XMLFilterImpl xMLFilterImpl0 = new XMLFilterImpl();
      // Undeclared exception!
      try {
        lSSITransformer0.start((ContentHandler) xMLFilterImpl0, (Target) null);
        fail("Expecting exception: RuntimeException");
      } catch(RuntimeException e) {
        /*
         * No SourceManager avaliable
         */
      }
  }
}
