/*
 * This file was automatically generated by EvoSuite
 */

package nu.staldal.lagoon.producer;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import java.io.IOException;
import java.io.OutputStream;
import nu.staldal.lagoon.core.LagoonException;
import nu.staldal.lagoon.core.Target;
import nu.staldal.lagoon.producer.XMLFormatter;
import org.xml.sax.SAXException;

public class XMLFormatterEvoSuiteTest {


  //Test case number: 0
  /*
   * 2 covered goals:
   * 1 nu.staldal.lagoon.producer.XMLFormatter.hasBeenUpdated(J)Z: root-Branch
   * 2 nu.staldal.lagoon.producer.XMLFormatter.<init>()V: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      XMLFormatter xMLFormatter0 = new XMLFormatter();
      // Undeclared exception!
      try {
        xMLFormatter0.hasBeenUpdated(3L);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  //Test case number: 1
  /*
   * 1 covered goal:
   * 1 nu.staldal.lagoon.producer.XMLFormatter.start(Ljava/io/OutputStream;Lnu/staldal/lagoon/core/Target;)V: root-Branch
   */
  @Test
  public void test1()  throws Throwable  {
      XMLFormatter xMLFormatter0 = new XMLFormatter();
      // Undeclared exception!
      try {
        xMLFormatter0.start((OutputStream) null, (Target) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  //Test case number: 2
  /*
   * 9 covered goals:
   * 1 nu.staldal.lagoon.producer.XMLFormatter.init()V: I16 Branch 1 IFNONNULL L66 - false
   * 2 nu.staldal.lagoon.producer.XMLFormatter.init()V: I30 Branch 2 IFNONNULL L71 - false
   * 3 nu.staldal.lagoon.producer.XMLFormatter.init()V: I85 Branch 6 IFLE L82 - false
   * 4 nu.staldal.lagoon.producer.XMLFormatter.init()V: I304 Branch 18 IFNULL L148 - true
   * 5 nu.staldal.lagoon.producer.XMLFormatter.init()V: I322 Branch 19 IFNULL L152 - true
   * 6 nu.staldal.lagoon.producer.XMLFormatter.init()V: I340 Branch 20 IFNULL L156 - true
   * 7 nu.staldal.lagoon.producer.XMLFormatter.init()V: I358 Branch 21 IFNULL L160 - true
   * 8 nu.staldal.lagoon.producer.XMLFormatter.init()V: I385 Branch 22 IFNULL L166 - true
   * 9 nu.staldal.lagoon.producer.XMLFormatter.<init>()V: root-Branch
   */
  @Test
  public void test2()  throws Throwable  {
      XMLFormatter xMLFormatter0 = new XMLFormatter();
      xMLFormatter0.init();
      assertEquals(0, xMLFormatter0.getPosition());
  }
}
