/*
 * This file was automatically generated by EvoSuite
 */

package br.com.jnfe.base;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import br.com.jnfe.base.CST_Grupo;

public class CST_GrupoEvoSuiteTest {



  //Test case number: 5
  /*
   * 3 covered goals:
   * 1 br.com.jnfe.base.CST_Grupo.isRequiredTag(Ljava/lang/String;)Z: I25 Branch 2 IFLE L164 - false
   * 2 br.com.jnfe.base.CST_Grupo.isRequiredTag(Ljava/lang/String;)Z: I15 Branch 1 IF_ICMPGE L163 - false
   * 3 br.com.jnfe.base.CST_Grupo.isRequiredTag(Ljava/lang/String;)Z: I25 Branch 2 IFLE L164 - true
   */
  @Test
  public void test5()  throws Throwable  {
      CST_Grupo cST_Grupo0 = CST_Grupo._SN500;
      boolean boolean0 = cST_Grupo0.isRequiredTag("vICMSSTRet");
      assertEquals(true, boolean0);
  }
}
