/*
 * This file was automatically generated by EvoSuite
 */

package br.com.jnfe.base;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import br.com.jnfe.base.IndTot;

public class IndTotEvoSuiteTest {


  //Test case number: 0
  /*
   * 1 covered goal:
   * 1 br.com.jnfe.base.IndTot.getValue()I: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      IndTot indTot0 = IndTot.NAO_SOMA;
      int int0 = indTot0.getValue();
      assertEquals(0, int0);
  }
}
