/*
 * This file was automatically generated by EvoSuite
 */

package br.com.jnfe.base;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import br.com.jnfe.base.TpDet;

public class TpDetEvoSuiteTest {


  //Test case number: 0
  /*
   * 1 covered goal:
   * 1 br.com.jnfe.base.TpDet.getValue()C: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      TpDet tpDet0 = TpDet.PRODUTO;
      char char0 = tpDet0.getValue();
      assertEquals('P', char0);
  }

  //Test case number: 1
  /*
   * 1 covered goal:
   * 1 br.com.jnfe.base.TpDet.isServico()Z: root-Branch
   */
  @Test
  public void test1()  throws Throwable  {
      TpDet tpDet0 = TpDet.PRODUTO;
      boolean boolean0 = tpDet0.isServico();
      assertEquals(false, boolean0);
  }
}
