/*
 * This file was automatically generated by EvoSuite
 */

package br.com.jnfe.base;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import br.com.jnfe.base.TpImp;

public class TpImpEvoSuiteTest {


  //Test case number: 0
  /*
   * 1 covered goal:
   * 1 br.com.jnfe.base.TpImp.getValue()C: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      TpImp tpImp0 = TpImp.PAISAGEM;
      char char0 = tpImp0.getValue();
      assertEquals('2', char0);
  }
}
