/*
 * This file was automatically generated by EvoSuite
 */

package net.sourceforge.schemaspy.model;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.SQLException;
import java.util.MissingResourceException;
import net.sourceforge.schemaspy.Config;
import net.sourceforge.schemaspy.model.Database;
import net.sourceforge.schemaspy.model.xml.SchemaMeta;

public class DatabaseEvoSuiteTest {


  //Test case number: 0
  /*
   * 9 covered goals:
   * 1 net.sourceforge.schemaspy.model.Database$CombinedMap.<init>(Lnet/sourceforge/schemaspy/model/Database;Ljava/util/Map;Ljava/util/Map;)V: root-Branch
   * 2 net.sourceforge.schemaspy.model.Database$NameValidator.<init>(Lnet/sourceforge/schemaspy/model/Database;Ljava/lang/String;Ljava/util/regex/Pattern;Ljava/util/regex/Pattern;[Ljava/lang/String;)V: I43 Branch 8 IF_ICMPGE L179 - true
   * 3 net.sourceforge.schemaspy.model.Database$NameValidator.<init>(Lnet/sourceforge/schemaspy/model/Database;Ljava/lang/String;Ljava/util/regex/Pattern;Ljava/util/regex/Pattern;[Ljava/lang/String;)V: I43 Branch 8 IF_ICMPGE L179 - false
   * 4 net.sourceforge.schemaspy.model.Database.getBasicTableMeta(Ljava/sql/DatabaseMetaData;Z[Ljava/lang/String;)Ljava/util/List;: I3 Branch 29 IFEQ L350 - false
   * 5 net.sourceforge.schemaspy.model.Database.getBasicTableMeta(Ljava/sql/DatabaseMetaData;Z[Ljava/lang/String;)Ljava/util/List;: I30 Branch 30 IFNULL L355 - true
   * 6 net.sourceforge.schemaspy.model.Database.getBasicTableMeta(Ljava/sql/DatabaseMetaData;Z[Ljava/lang/String;)Ljava/util/List;: I263 Branch 44 IFLE L387 - false
   * 7 net.sourceforge.schemaspy.model.Database.getTypes(Ljava/lang/String;Ljava/lang/String;)[Ljava/lang/String;: I31 Branch 50 IF_ICMPGE L429 - true
   * 8 net.sourceforge.schemaspy.model.Database.getTypes(Ljava/lang/String;Ljava/lang/String;)[Ljava/lang/String;: I31 Branch 50 IF_ICMPGE L429 - false
   * 9 net.sourceforge.schemaspy.model.Database.getTypes(Ljava/lang/String;Ljava/lang/String;)[Ljava/lang/String;: I45 Branch 51 IFLE L431 - false
   */
  @Test
  public void test0()  throws Throwable  {
      Config config0 = new Config();
      Database database0 = null;
      try {
        database0 = new Database(config0, (Connection) null, (DatabaseMetaData) null, "XZPH=7", "XZPH=7", "XZPH=7", (SchemaMeta) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
