/*
 * This file was automatically generated by EvoSuite
 */

package net.sourceforge.schemaspy.model;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import java.sql.SQLException;
import net.sourceforge.schemaspy.model.Database;
import net.sourceforge.schemaspy.model.Table;

public class TableEvoSuiteTest {


  //Test case number: 2
  /*
   * 1 covered goal:
   * 1 net.sourceforge.schemaspy.model.Table.<init>(Lnet/sourceforge/schemaspy/model/Database;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V: I59 Branch 6 IFNULL L87 - false
   */
  @Test
  public void test2()  throws Throwable  {
      Table table0 = null;
      try {
        table0 = new Table((Database) null, "^mMs;.:RM+\"HcO", "^mMs;.:RM+\"HcO", "^mMs;.:RM+\"HcO", "^mMs;.:RM+\"HcO");
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  //Test case number: 5
  /*
   * 4 covered goals:
   * 1 net.sourceforge.schemaspy.model.Table.getFullName(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;: I6 Branch 84 IFNONNULL L578 - false
   * 2 net.sourceforge.schemaspy.model.Table.getFullName(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;: I8 Branch 85 IFNONNULL L578 - false
   * 3 net.sourceforge.schemaspy.model.Table.getFullName(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;: I23 Branch 86 IFNONNULL L578 - false
   * 4 net.sourceforge.schemaspy.model.Table.getFullName(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;: I38 Branch 87 IFNONNULL L578 - false
   */
  @Test
  public void test5()  throws Throwable  {
      String string0 = Table.getFullName((String) null, (String) null, (String) null, "0");
      assertNotNull(string0);
      assertEquals("null.0", string0);
  }

  //Test case number: 6
  /*
   * 4 covered goals:
   * 1 net.sourceforge.schemaspy.model.Table.getFullName(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;: I8 Branch 85 IFNONNULL L578 - true
   * 2 net.sourceforge.schemaspy.model.Table.getFullName(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;: I6 Branch 84 IFNONNULL L578 - false
   * 3 net.sourceforge.schemaspy.model.Table.getFullName(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;: I23 Branch 86 IFNONNULL L578 - false
   * 4 net.sourceforge.schemaspy.model.Table.getFullName(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;: I38 Branch 87 IFNONNULL L578 - true
   */
  @Test
  public void test6()  throws Throwable  {
      String string0 = Table.getFullName("null.0", (String) null, "0", (String) null);
      assertNotNull(string0);
      assertEquals("0.null", string0);
  }
}
