/*
 * This file was automatically generated by EvoSuite
 */

package net.sf.lavalamp.site;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import net.sf.lavalamp.site.Console;

public class ConsoleEvoSuiteTest {


  //Test case number: 0
  /*
   * 2 covered goals:
   * 1 net.sf.lavalamp.site.Console.readLine(Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/String;: root-Branch
   * 2 net.sf.lavalamp.site.Console.<init>()V: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      Console console0 = new Console();
      Object[] objectArray0 = new Object[5];
      // Undeclared exception!
      try {
        console0.readLine((String) null, objectArray0);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  //Test case number: 1
  /*
   * 2 covered goals:
   * 1 net.sf.lavalamp.site.Console.readPassword(Ljava/lang/String;[Ljava/lang/Object;)[C: root-Branch
   * 2 net.sf.lavalamp.site.Console.<init>()V: root-Branch
   */
  @Test
  public void test1()  throws Throwable  {
      Console console0 = new Console();
      Object[] objectArray0 = new Object[6];
      // Undeclared exception!
      try {
        console0.readPassword("", objectArray0);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
