/*
 * This file was automatically generated by EvoSuite
 */

package net.sf.lavalamp.site;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import net.sf.lavalamp.site.DummyRemoteGetter;

public class AbstractGetterEvoSuiteTest {


  //Test case number: 0
  /*
   * 1 covered goal:
   * 1 net.sf.lavalamp.site.AbstractGetter.<init>()V: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      DummyRemoteGetter dummyRemoteGetter0 = new DummyRemoteGetter();
  }
}
