/*
 * This file was automatically generated by EvoSuite
 */

package net.sf.lavalamp.site;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import net.sf.lavalamp.properties.MissingPropertyException;
import net.sf.lavalamp.site.BuildProperties;
import net.sf.lavalamp.site.SiteProperties;

public class BuildPropertiesEvoSuiteTest {


  //Test case number: 0
  /*
   * 2 covered goals:
   * 1 net.sf.lavalamp.site.BuildProperties.toString()Ljava/lang/String;: root-Branch
   * 2 net.sf.lavalamp.site.BuildProperties.<init>()V: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      BuildProperties buildProperties0 = new BuildProperties();
      String string0 = buildProperties0.toString();
      assertNotNull(string0);
      assertEquals("\n\t\tbuildId=null,  null", string0);
  }

  //Test case number: 1
  /*
   * 1 covered goal:
   * 1 net.sf.lavalamp.site.BuildProperties.getSiteProperties()Lnet/sf/lavalamp/site/SiteProperties;: root-Branch
   */
  @Test
  public void test1()  throws Throwable  {
      BuildProperties buildProperties0 = new BuildProperties();
      SiteProperties siteProperties0 = buildProperties0.getSiteProperties();
      assertNull(siteProperties0);
  }

  //Test case number: 2
  /*
   * 1 covered goal:
   * 1 net.sf.lavalamp.site.BuildProperties.getBuild()Ljava/lang/String;: root-Branch
   */
  @Test
  public void test2()  throws Throwable  {
      BuildProperties buildProperties0 = new BuildProperties();
      String string0 = buildProperties0.getBuild();
      assertNull(string0);
  }

  //Test case number: 3
  /*
   * 1 covered goal:
   * 1 net.sf.lavalamp.site.BuildProperties.setSiteProperties(Lnet/sf/lavalamp/site/SiteProperties;)V: root-Branch
   */
  @Test
  public void test3()  throws Throwable  {
      BuildProperties buildProperties0 = new BuildProperties();
      buildProperties0.setSiteProperties((SiteProperties) null);
      assertEquals("\n\t\tbuildId=null,  null", buildProperties0.toString());
  }

  //Test case number: 4
  /*
   * 2 covered goals:
   * 1 net.sf.lavalamp.site.BuildProperties.check()V: I4 Branch 1 IFNONNULL L15 - true
   * 2 net.sf.lavalamp.site.BuildProperties.setBuild(Ljava/lang/String;)V: root-Branch
   */
  @Test
  public void test4()  throws Throwable  {
      BuildProperties buildProperties0 = new BuildProperties();
      buildProperties0.setBuild("");
      buildProperties0.check();
      assertEquals("\n\t\tbuildId=,  null", buildProperties0.toString());
  }

  //Test case number: 5
  /*
   * 2 covered goals:
   * 1 net.sf.lavalamp.site.BuildProperties.check()V: I4 Branch 1 IFNONNULL L15 - false
   * 2 net.sf.lavalamp.site.BuildProperties.<init>()V: root-Branch
   */
  @Test
  public void test5()  throws Throwable  {
      BuildProperties buildProperties0 = new BuildProperties();
      // Undeclared exception!
      try {
        buildProperties0.check();
        fail("Expecting exception: MissingPropertyException");
      } catch(MissingPropertyException e) {
        /*
         * build must be specified in properties file
         */
      }
  }
}
