/*
 * This file was automatically generated by EvoSuite
 */

package org.jsecurity.aop;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import org.jsecurity.aop.MethodInvocation;
import org.jsecurity.authz.AuthorizationException;
import org.jsecurity.authz.aop.RoleAnnotationMethodInterceptor;

public class AnnotationMethodInterceptorEvoSuiteTest {


  //Test case number: 0
  /*
   * 4 covered goals:
   * 1 org.jsecurity.aop.AnnotationMethodInterceptor.getHandler()Lorg/jsecurity/aop/AnnotationHandler;: root-Branch
   * 2 org.jsecurity.aop.AnnotationMethodInterceptor.getAnnotation(Lorg/jsecurity/aop/MethodInvocation;)Ljava/lang/annotation/Annotation;: I3 Branch 2 IFNONNULL L84 - false
   * 3 org.jsecurity.aop.AnnotationMethodInterceptor.<init>(Lorg/jsecurity/aop/AnnotationHandler;)V: root-Branch
   * 4 org.jsecurity.aop.AnnotationMethodInterceptor.setHandler(Lorg/jsecurity/aop/AnnotationHandler;)V: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      RoleAnnotationMethodInterceptor roleAnnotationMethodInterceptor0 = new RoleAnnotationMethodInterceptor();
      // Undeclared exception!
      try {
        roleAnnotationMethodInterceptor0.assertAuthorized((MethodInvocation) null);
        fail("Expecting exception: IllegalArgumentException");
      } catch(IllegalArgumentException e) {
        /*
         * method argument cannot be null
         */
      }
  }
}
