/*
 * This file was automatically generated by EvoSuite
 */

package net.sf.lavalamp.application;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import net.sf.lavalamp.Pause;
import net.sf.lavalamp.application.AlwaysOff;
import net.sf.lavalamp.application.WebRun;

public class AlwaysOffEvoSuiteTest {


  //Test case number: 0
  /*
   * 2 covered goals:
   * 1 net.sf.lavalamp.application.AlwaysOff.run()V: root-Branch
   * 2 net.sf.lavalamp.application.AlwaysOff.<init>(Lnet/sf/lavalamp/application/WebRun;Lnet/sf/lavalamp/Pause;)V: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      AlwaysOff alwaysOff0 = new AlwaysOff((WebRun) null, (Pause) null);
      // Undeclared exception!
      try {
        alwaysOff0.run();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
